CC = clang++
CC_FLAGS = -g -Wall -Wextra

STD = c++14
BINARYTREE = BinaryTree.cpp

# main target
binarytree: BinaryTree.cpp 
	$(CC) \
	$(CC_FLAGS) \
	-std=$(STD) \
	$(BINARYTREE) \
	-o BinaryTree.o









